site_name: Chunky Manual
site_url: https://chunky-dev.github.io/docs/
repo_url: https://github.com/chunky-dev/chunky
repo_name: chunky-dev/chunky
edit_uri: https://github.com/chunky-dev/docs/edit/master/ChunkyDocs/docs/

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/theme_override/

plugins:
    - redirects:
        redirect_maps:
            'getting_started/index.md': 'getting_started/installing_chunky.md'
            'getting_started/installing.md': 'getting_started/installing_chunky.md'
            'getting_started/configuration.md': 'getting_started/configuring_chunky_launcher.md'
            'rendering/index.md': 'reference/introduction/path_tracing.md'
            'rendering/denoising.md': 'reference/other_topics/denoising.md'
            'user_interface/index.md': 'reference/user_interface/chunky_gui.md'
            'user_interface/render/scene.md': 'reference/user_interface/render_controls/scene.md'
            'user_interface/render/lighting.md': 'reference/user_interface/render_controls/lighting.md'
            'user_interface/render/sky_and_fog.md': 'reference/user_interface/render_controls/sky_and_fog.md'
            'user_interface/render/water.md': 'reference/user_interface/render_controls/water.md'
            'user_interface/render/camera.md': 'reference/user_interface/render_controls/camera.md'
            'user_interface/render/entities.md': 'reference/user_interface/render_controls/entities.md'
            'user_interface/render/materials.md': 'reference/user_interface/render_controls/materials.md'
            'user_interface/render/postprocessing.md': 'reference/user_interface/render_controls/postprocessing.md'
            'user_interface/render/advanced.md': 'reference/user_interface/render_controls/advanced.md'
            'user_interface/render/help.md': 'reference/user_interface/render_controls/help.md'
            'user_interface/render/render_preview.md': 'reference/user_interface/render_preview.md'
            'user_interface/headless.md': 'reference/user_interface/headless.md'
            'rendering/scene_format.md': 'reference/technical/scene_format.md'
            'rendering/skymaps.md': 'reference/other_topics/skymaps.md'
            'user_interface/style.md': 'reference/other_topics/styling_chunky.md'
            'plugins/index.md': 'plugins/chunky_plugins.md'
            'plugins/plugins.md': 'plugins/plugin_list.md'
            'plugins/development.md': 'plugins/plugin_development.md'
            'faq/index.md': 'support/faq.md'
            'faq/troubleshooting.md': 'support/troubleshooting.md'
            'faq/minecraft_compatibility.md': 'support/minecraft_compatibility.md'
            'user_interface/chunky_ui.md': 'reference/user_interface/chunky_gui.md'
            'user_interface/render.md': 'reference/user_interface/render_controls/index.md'
            'gallery/index.md': 'https://chunky-dev.github.io/gallery/'
            'gallery/old_gallery.md': 'https://chunky-dev.github.io/gallery/old_gallery/'
    - search:
        lang: en
    - macros
    - mkdocs-simple-hooks:
        hooks:
          on_post_page: scripts.hooks:on_post_page
          on_nav: scripts.hooks:on_nav

extra_css:
  - extra/extra.css

markdown_extensions:
  - admonition
  - abbr
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.magiclink:
      repo_url_shorthand: true
      provider: github
      user: chunky-dev
      repo: chunky
  - tables
  - toc:
      permalink: true

copyright: The Chunky Manual is licensed under a CC-BY-NC-SA 4.0 Int. License (<a href="/docs/license">learn more</a>)

nav:
  - "Home": "index.md"
  - "Getting Started":
    - "Installing Chunky": "getting_started/installing_chunky.md"
    - "Configuring Chunky Launcher": "getting_started/configuring_chunky_launcher.md"
    - "Your First Render": "getting_started/your_first_render.md"
  - "Support":
    - "FAQ": "support/faq.md"
    - "Troubleshooting": "support/troubleshooting.md"
    - "Minecraft Compatibility": "support/minecraft_compatibility.md"
  - "Reference":
    - "Introduction":
      - "Path Tracing": "reference/introduction/path_tracing.md"
      - "Samples and Noise": "reference/introduction/samples_and_noise.md"
      - "Next Event Estimation": "reference/introduction/next_event_estimation.md"
      - "Material Properties": "reference/introduction/material_properties.md"
    - "User Interface":
      - "Chunky GUI": "reference/user_interface/chunky_gui.md"
      - "Menu Bar":
        - "File (Scene Management)": "reference/user_interface/menu_bar/file.md"
        - "Help (Chunky Resources)": "reference/user_interface/menu_bar/help.md"
      - "Scene Management": "reference/user_interface/scene_management.md"
      - "Map": "reference/user_interface/map.md"
      - "Render Preview": "reference/user_interface/render_preview.md"
      - "Right Panel Controls":
        - "Map View": "reference/user_interface/right_panel_controls/map_view.md"
        - "Chunks": "reference/user_interface/right_panel_controls/chunks.md"
        - "Options": "reference/user_interface/right_panel_controls/options.md"
        - "About": "reference/user_interface/right_panel_controls/about.md"
      - "Render Controls (Left Panel)":
        - "Scene": "reference/user_interface/render_controls/scene.md"
        - "Lighting": "reference/user_interface/render_controls/lighting.md"
        - "Sky & Fog": "reference/user_interface/render_controls/sky_and_fog.md"
        - "Water": "reference/user_interface/render_controls/water.md"
        - "Camera": "reference/user_interface/render_controls/camera.md"
        - "Entities": "reference/user_interface/render_controls/entities.md"
        - "Materials": "reference/user_interface/render_controls/materials.md"
        - "Postprocessing": "reference/user_interface/render_controls/postprocessing.md"
        - "Textures & Resource Packs": "reference/user_interface/render_controls/textures_and_resource_packs.md"
        - "Advanced": "reference/user_interface/render_controls/advanced.md"
        - "Help": "reference/user_interface/render_controls/help.md"
        - "Render Progress Controls": "reference/user_interface/render_controls/render_progress_controls.md"
      - "Headless (Command Line)": "reference/user_interface/headless.md"
    - "Other Topics":
      - "Denoising": "reference/other_topics/denoising.md"
      - "Skymaps": "reference/other_topics/skymaps.md"
      - "Styling Chunky": "reference/other_topics/styling_chunky.md"
    - "Technical":
      - "Scene Format": "reference/technical/scene_format.md"
  - "Plugins":
    - "Chunky Plugins": "plugins/chunky_plugins.md"
    - "Plugin List": "plugins/plugin_list.md"
    - "Plugin Development": "plugins/plugin_development.md"
  - "Gallery": "https://chunky-dev.github.io/gallery/"



extra:
  social:
    - name: Chunky Discord
      icon: fontawesome/brands/discord
      link: https://discord.gg/VqcHpsF
    - name: Chunky Subreddit
      icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/chunky/
    - name: Chunky GitHub
      icon: fontawesome/brands/github
      link: https://github.com/chunky-dev
  chunky: !ENV [CHUNKY_VERSION, 2_05_00]
  version:
    provider: mike
