site_name: Chunky Manual
site_url: https://chunky-dev.github.io/docs/
repo_url: https://github.com/chunky-dev/docs
edit_uri: edit/master/ChunkyDocs/docs/
theme:
  name: readthedocs

markdown_extensions:
  - admonition

nav:
  - "Home": "index.md"
  - "Getting Started":
    - "Installing Chunky": "getting_started/installing.md"
    - "Configuring Chunky": "getting_started/configuring.md"
    - "Your First Render": "getting_started/your_first_render.md"
  - "User Interface":
    - "Render Controls":
      - "Scene": "user_interface/render/scene.md"
      - "Lighting": "user_interface/render/lighting.md"
  - "Miscellaneous":
    - "Plugins": "plugins/index.md"
