site_name: Chunky Manual
site_url: https://chunky-dev.github.io/docs/
repo_url: https://github.com/chunky-dev/chunky
repo_name: chunky-dev/chunky
edit_uri: https://github.com/chunky-dev/docs/edit/master/ChunkyDocs/docs/

theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/theme_override/

plugins:
    - redirects:
        redirect_maps:
            # gallery
            'gallery/index.md': 'https://chunky-dev.github.io/gallery/'
            'gallery/old_gallery.md': 'https://chunky-dev.github.io/gallery/old_gallery/'

            # chunky.llbit.se
            'news.md': 'index.md'
            'download.md': 'getting_started/installing_chunky.md'
            'chunky2.md': 'index.md'
            'faq.md': 'support/faq.md'
            'troubleshooting.md': 'support/troubleshooting.md'
            'getting_started.md': 'getting_started/installing_chunky.md'
            'your_first_render.md': 'getting_started/your_first_render.md'
            'install.md': 'getting_started/installing_chunky.md'
            'tips.md': 'user_guides/introduction/samples_and_noise.md'
            'user_interface.md': 'reference/user_interface/chunky/chunky_gui.md'
            '2d_map.md': 'reference/user_interface/chunky/map.md'
            '2d_map_map-view.md': 'reference/user_interface/chunky/right_panel_controls/map_view.md'
            '2d_map_chunks.md': 'reference/user_interface/chunky/right_panel_controls/chunks.md'
            '2d_map_view_highlight.md': 'reference/user_interface/chunky/right_panel_controls/map_view.md'
            '2d_map_view_options.md': 'reference/user_interface/chunky/right_panel_controls/options.md'
            '2d_map_3d-render.md': 'reference/user_interface/chunky/render_controls/scene.md'
            'render_controls.md': 'reference/user_interface/chunky/render_controls/scene.md'
            'render_controls_general.md': 'reference/user_interface/chunky/render_controls/scene.md'
            'render_controls_lighting.md': 'reference/user_interface/chunky/render_controls/lighting.md'
            'render_controls_sky.md': 'reference/user_interface/chunky/render_controls/sky_and_fog.md'
            'render_controls_camera.md': 'reference/user_interface/chunky/render_controls/camera.md'
            'render_controls_post-processing.md': 'reference/user_interface/chunky/render_controls/postprocessing.md'
            'render_controls_advanced.md': 'reference/user_interface/chunky/render_controls/advanced.md'
            'render_controls_global.md': 'reference/user_interface/chunky/render_controls/render_progress_controls.md'
            'render_preview.md': 'reference/user_interface/chunky/render_preview.md'
            'path_tracing.md': 'user_guides/introduction/path_tracing.md'
            'headless.md': 'reference/user_interface/chunky_launcher/headless.md'
            'scene_format.md': 'reference/technical/scene_format.md'
            'minecraft_compatibility.md': 'support/minecraft_compatibility.md'
            'plugin_api.md': 'plugins/plugin_development.md'
            'skymaps.md': 'user_guides/skymaps.md'

            # Previous versions of the docs
            'reference/introduction/path_tracing.md': 'user_guides/introduction/path_tracing.md'
            'reference/introduction/samples_and_noise.md': 'user_guides/introduction/samples_and_noise.md'
            'reference/introduction/next_event_estimation.md': 'user_guides/introduction/next_event_estimation.md'
            'reference/introduction/material_properties.md': 'user_guides/introduction/material_properties.md'
            'reference/other_topics/denoising.md': 'user_guides/denoising.md'
            'reference/other_topics/skymaps.md': 'user_guides/skymaps.md'
            'reference/other_topics/styling_chunky.md': 'user_guides/styling_chunky.md'

    - search:
        lang: en
    - macros
    - mkdocs-simple-hooks:
        hooks:
          on_post_page: scripts.hooks:on_post_page
          on_nav: scripts.hooks:on_nav

extra_css:
  - extra/extra.css

markdown_extensions:
  - admonition
  - abbr
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.magiclink:
      repo_url_shorthand: true
      provider: github
      user: chunky-dev
      repo: chunky
  - tables
  - toc:
      permalink: true

copyright: The Chunky Manual is licensed under a CC-BY-NC-SA 4.0 Int. License (<a href="/docs/license">learn more</a>)

nav:
  - "Home": "index.md"
  - "Getting Started":
    - "Installing Chunky": "getting_started/installing_chunky.md"
    - "Configuring the Chunky Launcher": "getting_started/configuring_chunky_launcher.md"
    - "Your First Render": "getting_started/your_first_render.md"
  - "Support":
    - "FAQ": "support/faq.md"
    - "Troubleshooting": "support/troubleshooting.md"
    - "Minecraft Compatibility": "support/minecraft_compatibility.md"
  - "User Guides":
    - "Introduction":
      - "Path Tracing": "user_guides/introduction/path_tracing.md"
      - "Samples and Noise": "user_guides/introduction/samples_and_noise.md"
      - "Next Event Estimation": "user_guides/introduction/next_event_estimation.md"
      - "Material Properties": "user_guides/introduction/material_properties.md"
    - "Denoising": "user_guides/denoising.md"
    - "Skymaps": "user_guides/skymaps.md"
    - "Styling Chunky": "user_guides/styling_chunky.md"
  - "Reference":
    - "User Interface":
      - "Chunky Launcher":
        - "Chunky Launcher GUI": "reference/user_interface/chunky_launcher/chunky_launcher_gui.md"
        - "Headless (Command Line)": "reference/user_interface/chunky_launcher/headless.md"
      - "Chunky":
        - "Chunky GUI": "reference/user_interface/chunky/chunky_gui.md"
        - "Menu Bar":
          - "File (Scene Management)": "reference/user_interface/chunky/menu_bar/file.md"
          - "Help (Chunky Resources)": "reference/user_interface/chunky/menu_bar/help.md"
        - "Scene Management": "reference/user_interface/chunky/scene_management.md"
        - "Map": "reference/user_interface/chunky/map.md"
        - "Render Preview": "reference/user_interface/chunky/render_preview.md"
        - "Right Panel Controls":
          - "Map View": "reference/user_interface/chunky/right_panel_controls/map_view.md"
          - "Chunks": "reference/user_interface/chunky/right_panel_controls/chunks.md"
          - "Options": "reference/user_interface/chunky/right_panel_controls/options.md"
          - "About": "reference/user_interface/chunky/right_panel_controls/about.md"
        - "Render Controls (Left Panel)":
          - "Scene": "reference/user_interface/chunky/render_controls/scene.md"
          - "Lighting": "reference/user_interface/chunky/render_controls/lighting.md"
          - "Sky & Fog": "reference/user_interface/chunky/render_controls/sky_and_fog.md"
          - "Water": "reference/user_interface/chunky/render_controls/water.md"
          - "Camera": "reference/user_interface/chunky/render_controls/camera.md"
          - "Entities": "reference/user_interface/chunky/render_controls/entities.md"
          - "Materials": "reference/user_interface/chunky/render_controls/materials.md"
          - "Postprocessing": "reference/user_interface/chunky/render_controls/postprocessing.md"
          - "Textures & Resource Packs": "reference/user_interface/chunky/render_controls/textures_and_resource_packs.md"
          - "Advanced": "reference/user_interface/chunky/render_controls/advanced.md"
          - "Help": "reference/user_interface/chunky/render_controls/help.md"
          - "Render Progress Controls": "reference/user_interface/chunky/render_controls/render_progress_controls.md"
    - "Technical":
      - "Scene Format": "reference/technical/scene_format.md"
  - "Plugins":
    - "Chunky Plugins": "plugins/chunky_plugins.md"
    - "Plugin List": "plugins/plugin_list.md"
    - "Plugin Development": "plugins/plugin_development.md"
  - "Gallery": "https://chunky-dev.github.io/gallery/"

extra:
  social:
    - name: Chunky Discord
      icon: fontawesome/brands/discord
      link: https://discord.gg/VqcHpsF
    - name: Chunky Subreddit
      icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/chunky/
    - name: Chunky GitHub
      icon: fontawesome/brands/github
      link: https://github.com/chunky-dev
  chunky: !ENV [CHUNKY_VERSION, 2_05_00]
  version:
    provider: mike
