name: GitHub Pages Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Setup Python
        run: |
          python -m venv ./venv --clear
          source ./venv/bin/activate
          pip install -r ./requirements.txt
      - name: Build and Deploy
        run: |
          source ./venv/bin/activate
          cd ChunkyDocs
          python -m mkdocs gh-deploy --force
