name: GitHub Pages Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Setup Python
        run: |
          python -m venv ./venv --clear
          source ./venv/bin/activate
          pip install -r ./requirements.txt
      - name: Build and Deploy
        run: |
          source ./venv/bin/activate
          ./build.sh
      - name: Deploy to GH Pages
        run: |
          pip install ghp-import
          ghp-import --push --force --no-history --no-jekyll \
            --message="Deployed $(git rev-parse --short HEAD)" \
            ./docs/
