name: Pull Request Build
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Setup Python
        run: |
          python -m venv ./venv --clear
          source ./venv/bin/activate
          pip install -r ./requirements.txt

      - name: Build docs
        run: |
          source ./venv/bin/activate
          cd ChunkyDocs
          python -m mkdocs build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: site
          path: ./ChunkyDocs/site/
          if-no-files-found: error
