name: Pull Request Build
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: |
          cd ChunkyDocs
          mkdocs build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: site
          path: ./ChunkyDocs/site/
          if-no-files-found: error
