name: Pull Request Build

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Setup Python
        run: |
          python -m venv ./venv --clear
          source ./venv/bin/activate
          pip install -r ./requirements.txt

      - name: Build docs
        run: |
          source ./venv/bin/activate
          ./build.sh
          test -f ./docs/index.html # sanity check

      - name: Save PR Number
        run: echo ${{ github.event.number }} > ./docs/pr-number.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: site
          path: ./docs/
          if-no-files-found: error
