name: Pull Request Teardown

on:
  pull_request_target:
    types:
      - closed

concurrency:
  group: pr-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  teardown:
    runs-on: ubuntu-latest

    steps:
      - name: Setup NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Surge
        run: npm install -g surge

      - name: Teardown Surge
        run: |
          surge teardown https://chunky-dev-docs-pr-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }} || true

      - name: Update Comment
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            PR Preview has been destroyed since this PR is closed.
            
            <!-- Sticky Pull Request Comment -->
          body-include: "<!-- Sticky Pull Request Comment -->"
          number: ${{ github.event.pull_request.number }}
